################################
# LOCAL OLLAMA CONFIGURATION:
################################
# OFFICIAL DOCUMENTATION:
# https://aider.chat/docs/config/options.html#:~:text=You%20can%20use%20aider%20--help%20to%20see%20all,store%20your%20API%20keys.%20%5B--openai-api-base%5D%20%5B--openai-api-type%5D%20%5B--openai-api-version%5D%20%5B--openai-api-deployment-id%5D
# OFFICIAL DOCUMENTATION 02:
# https://aider.chat/docs/config/aider_conf.html

# 1. Uncomment below model and api base URL
# 2. Run Ollama locally with:
#    export OLLAMA_API_BASE=http://127.0.0.1:11434
#    ollama serve

# model: ollama_chat/qwen2.5:7b
# model: ollama_chat/gemma3:12b
# model: ollama_chat/gemma3:4b
# model: ollama_chat/qwen3:30b-a3b  # Mixture of experts model

# Option 1: working with ollama
# openai-api-base: http://localhost:11434

# Option 2: working with open router
openai-api-base: https://openrouter.ai/api/v1/chat/completions

################################
# STRONG MODEL (OpenRouter):
# For complex reasoning and large changes
################################
# option 1: deep seek r1
# model: openrouter/deepseek/deepseek-r1:free

# option 2: deep seel r1 2025.05.28
# Created May 28, 2025
# 163,840 context $0/M input tokens $0/M output tokens
# model: openrouter/deepseek/deepseek-r1-0528:free

# option 3:
# see: https://openrouter.ai/tngtech/deepseek-r1t2-chimera:free
# Created Jul 8, 2025 163,840 context $0/M input tokens $0/M output tokens
model: openrouter/tngtech/deepseek-r1t2-chimera:free

# option 4:
# https://openrouter.ai/openrouter/cypher-alpha:free
#This is a cloaked model provided to the community to gather feedback. It's an all-purpose model supporting real-world, long-context tasks including code generation.
#Note: All prompts and completions for this model are logged by the provider and may be used to improve the model and other products and services. You remain responsible for any required end user notices and consents and for ensuring that no personal, confidential, or otherwise sensitive information, including data from individuals under the age of 18, is submitted.
# model: openrouter/cypher-alpha:free


################################
# EDIT MODEL (OpenRouter):
# For quick code edits and simple tasks
################################
# quote: Specify the model to use for editor tasks (default depends on –model)
# quote: Environment variable: AIDER_EDITOR_MODEL

# option 1:
# see: https://openrouter.ai/tngtech/deepseek-r1t2-chimera:free
editor-model: openrouter/tngtech/deepseek-r1t2-chimera:free

# option 2:
# editor-model: openrouter/deepseek/deepseek-r1-0528-qwen3-8b:free

################################
# WEAK MODEL (OpenRouter):
# Commit messages
################################
# Specify the model to use for commit messages and chat history summarization (default depends on –model)
# Environment variable: AIDER_WEAK_MODEL
# Created May 27, 2024
# 32,768 context $0/M input tokens $0/M output tokens
# https://openrouter.ai/mistralai/mistral-7b-instruct:free

# option 1:
# weak-model: openrouter/mistralai/mistral-7b-instruct:free

# option 2:
# https://openrouter.ai/mistralai/devstral-small-2505:free
# Created May 21, 2025 # 32,768 context # $0/M input tokens # $0/M output tokens
weak-model: openrouter/mistralai/devstral-small-2505:free

# option 2:
# weak-model: openrouter/deepseek/deepseek-r1-0528-qwen3-8b:free


###############
# Git Settings:

## Enable/disable looking for a git repo (default: True)
git: true

## Enable/disable adding .aider* to .gitignore (default: True)
gitignore: false

## Specify the aider ignore file (default: .aiderignore in git root)
aiderignore: .aiderignore

## Only consider files in the current subtree of the git repository
#subtree-only: false

## Enable/disable auto commit of LLM changes (default: True)
auto-commits: false

## Run aider in your browser
#gui: false

## Enable/disable suggesting shell commands (default: True)
#suggest-shell-commands: true

#set-env:
  # For OpenRouter (required for strong model):
  # - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
  
  # For local Ollama (optional for weak model):
  # - OLLAMA_API_BASE=http://127.0.0.1:11434

